[tool.black]
line-length = 100
include = '\\.(py)$'

[tool.ruff]
line-length = 100
target-version = 'py313'

[tool.ruff.lint]
select = [
    'E',  # pycodestyle errors
    'F',  # pyflakes
    'I',  # isort
]
ignore = []

[tool.ruff.format]
indent-style = 'space'
quote-style = 'single'
line-ending = 'auto'

